### ISSUE TITLE
`DBCreationScript.txt` is missing

### ISSUE THREAD

**Issue by WolfgangRamos** [vkhorikov/AnemicDomainModel#12]
Hi @vkhorikov, 

when I look into the `README.md` file of this repository with a normal text editor, I see that there is an unused reference-link to `[L2]: DBCreationScript.txt` at the bottom of the file. I would expect that file to be in the top level directory of the repository, but it isn't anywhere in the repository. Would you consider adding it to the repository to help trainees get the database up and running?

Btw, I am very much enjoying your pluralsight course(s), awesome work 👍

**Comment by vkhorikov** [comment]
This should be it: https://github.com/vkhorikov/AnemicDomainModel/blob/master/After/src/Database.sql

**Comment by WolfgangRamos** [comment]
Perfect, thanks.
